# RBAC authn and authz
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging
  namespace: logging
  # namespace: kube-system
  labels:
    app: logging
    kubernetes.io/cluster-service: "true"
    # addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging
  labels:
    app: logging
    kubernetes.io/cluster-service: "true"
    # addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: logging
  # namespace: kube-system
  name: logging
  labels:
    app: logging
    kubernetes.io/cluster-service: "true"
    # addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: logging
  namespace: logging
  # namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: logging
  apiGroup: ""