version: '3.8'
networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    # restart: always
    # restart: unless-stopped
    working_dir: /var/lib/prometheus/
    volumes:
      # - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ${PWD}/prometheus/node-exporter.json:/etc/prometheus/targets/node-exporter.json
      - ${PWD}/prometheus:/etc/prometheus
      - /var/lib/prometheus:/var/lib/prometheus
    command:
    # args: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # - "--storage.local.path=/var/lib/prometheus"
      # - "--storage.local.memory-chunks=10000"
      - '--storage.tsdb.path=/var/lib/prometheus/data'
      - '--storage.tsdb.retention=15d'
      # - '--log.level=info'
      # - '--web.listen-address=0.0.0.0:9090'
      # - '--query.max-concurrency=50'
    ports:
      - '9090:9090'
    networks:
      - monitor      
    expose:
      - "9090"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    # restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - '9100:9100'
    networks:
      - monitor
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    # entrypoint: ["echo", "Service foo disabled"]
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    # restart: always
    volumes:
      - ${PWD}/alertmanager/config.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    networks:
      - monitor
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    # restart: always
    volumes:
      - /var/log/grafana:/var/log/grafana
      - /var/lib/grafana:/var/lib/grafana
    environment:
      # - GF_SERVER_ROOT_URL=https://YOUR.DOMAIN.TEST
      # - GF_SERVER_DOMAIN=YOUR.DOMAIN.TEST
      # - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_SECURITY_ADMIN_USER=SECURE_USERNAME
      - GF_SECURITY_ADMIN_PASSWORD=passw0rd
    ports:
      - "3000:3000"
      - "25:25"
    networks:
      - monitor
    depends_on:
      - prometheus