version: '3.8'

volumes:
  redis_data:
  mysql_data:
  elasticsearch_data:

networks:
  frontend:
  backend:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    restart: always
    networks:
      - backend
