version: '3.8'

services:
  redis:
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - test
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:r
      - /var/lib/redis:/var/lib/redis:rw
      - /var/log/redis:/var/log/redis
    command:
#      redis-server /etc/redis/redis.conf --appendonly yes
#      /bin/bash -c "
#      echo 511 > /proc/sys/net/core/somaxconn && echo never > /sys/kernel/mm/transparent_hugepage/enabled \
      entrypoint.sh /usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: any # on-failure
      resources:
        limits:
          cpus: "1"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 10s
        max_failure_ratio: 0.1
        order: start-first
#volumes:
#  redis_data:

networks:
   test:
     external: true 