version: '3.8'

networks:
  outside:
  inside:

services:
  config:
    image: 127.0.0.1:5000/netkiller/config:latest
    ports:
      - "8888:8888"
    volumes:
      - /tmp/config:/tmp
    networks:
      - outside
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 256M
