apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-server
  namespace: default
  labels:
    app: springboot
spec:
  selector:
    app: spring-cloud-config-server
  type: ClusterIP
  ports: 
  - name: http
    protocol: TCP 
    port: 8888
    targetPort: 8888
  clusterIP: 10.10.0.2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-config-server
  labels:
    app: spring-cloud-config-server
data:
  application.properties: |-
    spring.application.name=config-server
    spring.profiles.active=native
    server.port=8888
    # server.ssl.enabled=true
    # server.ssl.key-store-type=PKCS12
    # server.ssl.key-store=classpath:localhost.p12
    # server.ssl.key-store-password=123456
    # #server.ssl.key-store=classpath:allhost.p12
    # #server.ssl.key-store-password=passw0rd
    # server.http2.enabled=true

    logging.file=/tmp/spring.log

    spring.security.user.name=config
    spring.security.user.password=s3cr3t

    #spring.cloud.config.server.git.uri=/opt/config
    spring.cloud.config.server.native.search-locations=classpath:/shared
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-config-server
  template:
    metadata:
      labels:
        app: spring-cloud-config-server
    spec:
      containers: 
      - name: spring-cloud-config-server
        #image: netkiller/config:latest
        #image: 127.0.0.1:5000/netkiller/config:latest
        image: registry.netkiller.cn:5000/netkiller/config:latest
        ports:
        - containerPort: 8888
        # resources:
        #   limits:
        #     cpu: 2000m
        #     memory: 2Gi
        #   requests:
        #     cpu: 1000m
        #     memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        env:
        - name: JAVA_OPTS
          value: -server -Xms128m -Xmx512m
        #   valueFrom:
        #     resourceFieldRef:
        #       resource: limits.memory
        #       divisor: 1Mi
        # - name: JAVA_OPTS
        #   value: -server -Xms512m -Xmx4096m -Duser.timezone="Asia/Shanghai" -Djava.security.egd=file:/dev/./urandom
        - name: SPRING_OPTS
          value: --spring.config.location=/srv/application.properties
        volumeMounts:
        - name: config
          mountPath:  /srv/application.properties
          subPath: application.properties
        # - name: logfile
        #   mountPath: /tmp          
      volumes:
      # - name: logfile
      #   emptyDir: {} 
      - name: config
        configMap:
          name: spring-cloud-config-server
      imagePullSecrets:
        - name: docker-hub