apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-restful
  namespace: default
  labels:
    app: springboot
spec:
  selector:
    app: spring-cloud-restful
  type: ClusterIP
  ports: 
  - name: http
    protocol: TCP 
    port: 8080
    targetPort: 8080
  clusterIP: 10.10.0.10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-cloud-restful
  labels:
    app: spring-cloud-restful
data:
  application.properties: |-
    spring.application.name=microservice-restful
    # server.address=eureka.cluster
    server.port=8080
    logging.file=/tmp/spring.log

    eureka.client.serviceUrl.defaultZone=http://eureka:s3cr3t@eureka.cluster:8761/eureka/
    eureka.instance.hostname=eureka.cluster
    eureka.instance.preferIpAddress=true
    eureka.instance.non-secure-port-enabled=false
    eureka.instance.secure-port-enabled=true
    eureka.instance.securePort=${server.port}

    #management.security.enabled=false
    #management.endpoints.enabled-by-default=false
    #management.endpoint.info.enabled=true
    #management.endpoints.web.exposure.include=*
    #management.endpoints.web.exposure.include=health,info,env,metrics,prometheus
    #management.endpoint.health.show-details=always

    logging.level.org.springframework.web.bind.annotation.RequestMapping=DEBUG
    # logging.level.org.springframework.web=DEBUG
    # logging.level.root=DEBUG
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-restful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-restful
  template:
    metadata:
      labels:
        app: spring-cloud-restful
    spec:
      hostAliases:
      - ip: "10.10.0.2"
        hostnames: 
        - "config.cluster"
      - ip: "10.10.0.3"
        hostnames:
        - "eureka.cluster"
      containers: 
      - name: spring-cloud-restful
        #image: netkiller/eureka:latest
        #image: 127.0.0.1:5000/netkiller/eureka:latest
        image: 192.168.3.85:5000/netkiller/restful:latest
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 2000m
        #     memory: 2Gi
        #   requests:
        #     cpu: 1000m
        #     memory: 1Gi
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 5
        #   failureThreshold: 12
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8080
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 5
        #   failureThreshold: 12
        env:
        - name: JAVA_OPTS
          value: -server -Xms512m -Xmx4096m
        #   valueFrom:
        #     resourceFieldRef:
        #       resource: limits.memory
        #       divisor: 1Mi
        # - name: JAVA_OPTS
        #   value: -server -Xms512m -Xmx4096m -Duser.timezone="Asia/Shanghai" -Djava.security.egd=file:/dev/./urandom
        - name: SPRING_OPTS
          value: --spring.config.location=/srv/application.properties
        volumeMounts:
        - name: config
          mountPath:  /srv/application.properties
          subPath: application.properties
        # - name: logfile
        #   mountPath: /tmp          
      volumes:
      # - name: logfile
      #   emptyDir: {} 
      - name: config
        configMap:
          name: spring-cloud-restful
      imagePullSecrets:
        - name: docker-hub