apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: default
  labels:
    app: springboot
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30000 #service对外开放端口
  selector:
    app: springboot
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: springboot #名称
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers: #docker容器的配置
      - name: springboot
        image: 192.168.3.85:5000/netkiller/config:latest # pull镜像的地址 ip:prot/dir/images:tag
        # imagePullPolicy: IfNotPresent #pull镜像时机，
        imagePullPolicy: Always #Never
        ports:
        - containerPort: 8888 #容器对外开放端口
#      imagePullSecrets:
#        - name: registry.gitlab.com